site_name: "Vision Chain"
repo_url: https://github.com/BinItAI/VisionChain

theme:
  name: "material"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
nav:     
  - Dataset Splitting: 'index.md'
  - Dataset Analysis: 'dataset_analysis.md'
  - Utils: 'index.md'
  - Evaluation: 'index.md'

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
- search:
    lang: en

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
